

# Site Settings
title: 						"lorosukmo"
email: 						"lorosukmo@live.com"
description: 				"Just Blogging"
baseurl: 					""
url: 						"http://lorosukmo.github.io"
logourl: 					"https://avatars3.githubusercontent.com/u/4507180?v=3&s=460"		
fa-logo: 					"fa-code"
paginate: 					5


# Groom
groom_name: 				"Sukmo Wijoyo"
groom_fb: 					"http://lorosukmo.github.io"
groom_tw: 					"http://lorosukmo.github.io"
groom_ig: 					"http://lorosukmo.github.io"
groom_bio: 					"Tukang ketik amatiran dan pemuja keindahan wanita"
groom_image: 				"https://avatars3.githubusercontent.com/u/4507180?v=3&s=460"

# Bridge
bridge_name: 				"Sukmo Wijoyo"
bridge_fb: 					"http://lorosukmo.github.io"
bridge_tw: 					"http://lorosukmo.github.io"
bridge_ig: 					"http://lorosukmo.github.io"
bridge_bio: 					"Tukang ketik amatiran dan pemuja keindahan wanita"
bridge_image: 				"https://avatars3.githubusercontent.com/u/4507180?v=3&s=460"

# Social Settings
twitter_url: 				"http://twitter.com/XaHaX"
facebook_url: 				"http://facebook.com/"
github_url:  				"http://github.com/lorosukmo"
youtube_url:  				"http://youtube.com"
dribbble_url:  				"http://dribbble.com"
googleplus_url: 			"http://google.com/plus"
instagram_url:  			"http://instagram.com/loro.sukmo"
pinterest_url:  			"http://pinterest.com"
linkedin_url:  				"http://linkedin.com"


# Theme Settings
theme_disqus_shortname: 	"lorosukmo"
theme_google_comments: 		false
theme_analytics_id: 		"UA-28077903-4"
theme_analytics_domain: 	"lorosukmo.github.io"
theme_reading_time: 		true
theme_autoload_comments: 	false
theme_always_show_nav: 		false


# SASS Settings
# DO NOT MODIFY
sass:
 sass_dir: "assets/css/"
 style: :compressed


# Build Settings
markdown: 					kramdown
permalink: 					pretty

